platform: linux

image_resource:
  type: docker-image
  source:
    repository: openjdk
    tag: '8-jdk'

inputs:
  - name: MYFirstSpringApp
  - name: version

outputs:
  - name: build-output

run:
  path: bash
  args:
  - -exc
  - |
    cd MYFirstSpringApp
    chmod +x gradlew
    ./gradlew -P version=$(cat ../version/number) build
    cp build/libs/MYFirstSpringApp-0.0.1-SNAPSHOT.jar ../build-output
